version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: library_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=LibraryDB
      - MYSQL_USER=library_user
      - MYSQL_PASSWORD=library_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d:ro

  adminer:
    image: adminer:latest
    container_name: library_adminer
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  db_data:
